### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by alannawalton** [ACM-HU/afrohacks#2]
_You can alter the wording but this is just a general idea of what to say. These are all the ones I could think of right now._ 

**Can I attend this event?**
Sure! If you are in the area and are at least 18 years of age you are welcome to come

**How much does it cost?**
AfroHacks is 100% free of charge to all registrants.

**How do I get there?**
Feel free to Uber into the area or take the Metro! If you decided to metro here be sure to get on the Green line and take it to the Shaw/Howard stop. Lewis K. Downing Hall is about a 10 minute walk from the station.

**What will I eat?**
We'll provide food for all meals from Friday's dinner to Saturday's dinner. If you have dietary restrictions we will try our best to accommodate them. Also there will be tons of snacks and drinks.

**What should I bring?**
Please bring a valid form of identification and a laptop. If you want to be comfortable we suggest also brining a blanket, pillows and slippers.

**I still have a question that I want answered**
Please email us at afrohackshu@gmail.com. We'd love to help out!

**Comment by aunyks** [comment]
Cool I'll probably commit them later
